site_name: Zoltar Documentation

nav:
  - Home: 'index.md'
  - User Guide:
      - 'Concepts': 'Concepts.md'
      - 'Data model': 'DataModel.md'
      - 'Zoltar Home page': 'HomePage.md'
      - 'Model detail page': 'ModelDetailPage.md'
      - 'Project detail page': 'ProjectDetailPage.md'
  - Researcher Guide:
      - 'Zoltr R library': 'Zoltr.md'
      - 'Zoltpy Python library': 'Zoltpy.md'
      - 'Data analysis': 'DataAnalysis.md'
  - Developer Guide:
      - 'RESTful API': 'Api.md'
      - 'Zoltr R library': 'Zoltr.md'
      - 'Zoltpy Python library': 'Zoltpy.md'

theme: material
