site_name: Zoltar Documentation

nav:
  - Home: 'index.md'
  - Web Tour: 'tour.md'
      - 'Zoltar Home page': 'HomePage.md'
      - 'Model detail page': 'ModelDetailPage.md'
      - 'Project detail page': 'ProjectDetailPage.md'
  - User Guide:
      - 'Introduction': 'UserIntro.md'
      - 'Concepts': 'Concepts.md'
      - 'Data model': 'DataModel.md'
  - Researcher Guide:
      - 'Introduction': 'ResearcherIntro.md'
      - 'Data analysis': 'DataAnalysis.md'
  - Developer Guide:
      - 'Introduction': 'DeveloperIntro.md'
      - 'File Formats': 'FileFormats.md'
      - 'RESTful API': 'Api.md'
  - zoltr Package:
      - 'Overview': 'ZoltrOverview.md'
      - 'Getting Started': 'ZoltrGettingStarted.md'
      - 'ProjectOwners': 'ZoltrProjectOwners.md'
  - zoltpy Library:
      - 'Overview': 'ZoltpyOverview.md'

theme: material
