site_name: Zoltar Documentation

nav:
  - Home: 'index.md'
  - Web Tour:
      - 'Introduction': 'WebTourIntro.md'
      - 'Zoltar Home page': 'HomePage.md'
      - 'Project detail page': 'ProjectDetailPage.md'
      - 'Model detail page': 'ModelDetailPage.md'
      - 'Forecast detail page': 'ForecastDetailPage.md'
  - User Guide:
      - 'Introduction': 'UserIntro.md'
      - 'Concepts': 'Concepts.md'
      - 'Targets': 'Targets.md'
      - 'Data model': 'DataModel.md'
      - 'Scoring': 'Scoring.md'
      - 'Visualizations': 'Visualizations.md'
      - 'Validation': 'Validation.md'
      - 'File Formats': 'FileFormats.md'
      - 'RESTful API': 'Api.md'
  - zoltr Package:
      - 'Overview': 'ZoltrOverview.md'
      - 'Getting Started': 'ZoltrGettingStarted.md'
      - 'ProjectOwners': 'ZoltrProjectOwners.md'
  - zoltpy Library:
      - 'Overview': 'ZoltpyOverview.md'

theme: material
